app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['uses'=>'UserController@posts']);
Route::get('users/{id}/posts', ['uses'=>'UserController@userPosts']);

Route::group(['middleware' => 'guest'], function () {
    /*
     * Sign in form
     */
    Route::get('sign-in', 
        ['as'=>'signIn', 'uses'=>'AuthController@signIn']
    );
    
    /*
     * Sign in handle
     */
    Route::post('sign-in', 
        ['as'=>'postSignIn', 'uses'=>'AuthController@postSignIn']
    );
    
    /*
     * Sign up form
     */
    Route::get('sign-up', 
        ['as'=>'signUp', 'uses'=>'AuthController@signUp']
    );
    
    /*
     * Sign up handle
     */
    Route::post('sign-up', 
        ['as'=>'postSignUp', 'uses'=>'AuthController@postSignUp']
    );
});

Route::group(['middleware' => 'auth'], function () {
    /*
     * posts
     */
    Route::resource('post', 'PostController');
    
    /*
     * Sign out handle
     */
    Route::get('sign-out', 
        ['as'=>'signOut', 'uses'=>'AuthController@signOut']
    );
});

resources/views/layouts/alert.blade.php
<!--alert-->
@if(session()->has('alert'))
<div class="container row-space-top-2 row-space-2">
    <div class="alert alert-dismissable {{ session('alert')['class'] }}">
        {{ session('alert')['message'] }}
    </div>
</div>
@endif

@if($errors->any())
<div class="container row-space-top-2 row-space-2">
    <ul class="alert alert-danger list-unstyled">
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<!--end alert-->

resources/views/layouts/default.blade.php
@include('layouts.header')

@section('nav_bar')
<header>
<nav class="navbar navbar-dzung">
    <div class="container">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand" href="{{ url('/') }}">
                  <img alt="Dung" src="{{ asset('web/img/logo.png') }}" height="35">
              </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              @if($userAuth)
                <li><a href="{{ route('post.index') }}">My Post</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ $userAuth->name }} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ route('signOut') }}">Log Out</a></li>
                  </ul>
                </li>
               @else
               <li><a href="{{ route('signIn') }}">Sign In</a></li>
               <li><a href="{{ route('signUp') }}">Sign Up</a></li>
                @endif
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </div>
</nav>
        
</header> <!--end header-->
@show

<div id="content">
    @include('layouts.alert')
    @yield('content')
</div>

@include('layouts.footer')

resources/views/layouts/footer.blade.php
<script type="text/javascript" src="{{ asset('web/js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript">
$(function () {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
});
</script>
@yield('script')
</body>
</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        @yield('title')

        <!-- Bootstrap -->
        <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ asset('bootstrap/css/bootstrap-theme.min.css') }}" rel="stylesheet">
        <!--end bootstrap-->
        
        <!--style site-->
        <link href="{{ asset('web/css/style.css') }}" rel="stylesheet">

        @yield('style')
    </head>
    <body>